# Generated by Django 4.2.3 on 2023-08-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctioncategory_alter_user_id_auctionlisting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
