# Generated by Django 4.2.3 on 2023-08-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auctionlisting_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="desctiprion",
            new_name="description",
        ),
    ]
