# Generated by Django 4.2.3 on 2023-08-05 16:10

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_auctionbid_auction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="image",
            field=models.ImageField(
                null=True, upload_to="auction_images/%Y/%m"
            ),
        ),
    ]
