# Generated by Django 4.2.3 on 2023-08-06 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_auctionbid_auction"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="watch_list",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watching_listing",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
