# Generated by Django 4.2.3 on 2023-08-08 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_auctionbid_date_time_auctionlisting_date_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="watch_list",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="watch_list",
            field=models.ManyToManyField(
                related_name="watching_listing", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
